# Generated by Django 5.1.3 on 2024-11-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cedula_vendedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_vendedor', models.CharField(max_length=50)),
                ('apellido_vendedor', models.CharField(max_length=50)),
                ('telefono_vendedor', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha_elaboracion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Factura.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('iva', models.IntegerField()),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Factura.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Factura.producto')),
                ('cedula_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Factura.vendedor')),
            ],
        ),
    ]
